
var sections = [
    { title: "Main Concepts", from: 0, to: 27 },
    { title: "Main Concepts 2", from: 28, to: 47 },
    { title: "Body", from: 48, to: 55 },
    { title: "Physics and Materials", from: 56, to: 69 },
    { title: "States", from: 70, to: 77 },
    { title: "Shapes", from: 78, to: 105 },
    { title: "Colors", from: 106, to: 117 },
];

var words = [
    "write", "would", "like", "these", "long", "make", "thing", "see", "two", "has", "look", "more", "day", "number", "sound", "no", "most", "people", "my", "over", "know", "water", "than", "call", "first", "who", "may", "down", "side", "been", "now", "find", "any", "new", "work", "part", "take", "get", "place", "made", "live", "where", "after", "back", "little", "only", "round", "man", "year", "came", "show", "every", "good", "me", "give", "our", "under", "name", "very", "through", "just", "form", "sentence", "great", "think", "say", "help", "low", "line", "differ", "turn", "cause", "much", "mean", "before", "move", "right", "boy", "old", "too", "same", "tell", "does", "set", "three", "want", "air", "well", "also", "play", "small", "end", "put", "home", "read", "hand", "port", "large", "spell", "add", "even", "land", "here", "must", "big", "high", "such", "follow", "act", "why", "ask", "men", "change", "went", "light", "kind", "off", "need", "house", "picture", "try", "us", "again", "animal", "point", "mother", "world", "near", "build", "self", "earth", "father", "head", "stand", "own", "page", "should", "country", "found", "answer", "school", "grow", "study", "still", "learn", "plant", "cover", "food", "sun", "four", "between", "state", "keep", "eye", "never", "last", "let", "thought", "city", "tree", "cross", "farm", "hard", "start", "might", "story", "saw", "far", "sea", "draw", "left", "late", "run", "don't", "while", "press", "close", "night", "real", "life", "few", "north", "open", "seem", "together", "next", "white", "children", "begin", "got", "walk", "example", "ease", "paper", "group", "always", "music", "those", "both", "mark", "often", "letter", "until", "mile", "river", "car", "feet", "care", "second", "book", "carry", "took", "science", "eat", "room", "friend", "began", "idea", "fish", "mountain", "stop", "once", "base", "hear", "horse", "cut", "sure", "watch", "color", "face", "wood", "main", "enough", "plain", "girl", "usual", "young", "ready", "above", "ever", "red", "list", "though", "feel", "talk", "bird", "soon", "body", "dog", "family", "direct", "pose", "leave", "song", "measure", "door", "product", "black", "short", "numeral", "class", "wind", "question", "happen", "complete", "ship", "area", "half", "rock", "order", "fire", "south", "problem", "piece", "told", "knew", "pass", "since", "top", "whole", "king", "space", "heard", "best", "hour", "better", "true", "during", "hundred", "five", "remember", "step", "early", "hold", "west", "ground", "interest", "reach", "fast", "verb", "sing", "listen", "six", "table", "travel", "less", "morning", "ten", "simple", "several", "vowel", "toward", "war", "lay", "against", "pattern", "slow", "center", "love", "person", "money", "serve", "appear", "road", "map", "rain", "rule", "govern", "pull", "cold", "notice", "voice", "unit", "power", "town", "fine", "certain", "fly", "fall", "lead", "cry", "dark", "machine", "note", "wait", "plan", "figure", "star", "box", "noun", "field", "rest", "correct", "able", "pound", "done", "beauty", "drive", "stood", "contain", "front", "teach", "week", "final", "gave", "green", "oh", "quick", "develop", "ocean", "warm", "free", "minute", "strong", "special", "mind", "behind", "clear", "tail", "produce", "fact", "street", "inch", "multiply", "nothing", "course", "stay", "wheel", "full", "force", "blue", "object", "decide", "surface", "deep", "moon", "island", "foot", "system", "busy", "test", "record", "boat", "common", "gold", "possible", "plane", "stead", "dry", "wonder", "laugh", "thousand", "ago", "ran", "check", "game", "shape", "equate", "hot", "miss", "brought", "heat", "snow", "tire", "bring", "yes", "distant", "fill", "east", "paint", "language", "among", "grand", "ball", "yet", "wave", "drop", "heart", "am", "present", "heavy", "dance", "engine", "position", "arm", "wide", "sail", "material", "size", "vary", "settle", "speak", "weight", "general", "ice", "matter", "circle", "pair", "include", "divide", "syllable", "felt", "perhaps", "pick", "sudden", "count", "square", "reason", "length", "represent", "art", "subject", "region", "energy", "hunt", "probable", "bed", "brother", "egg", "ride", "cell", "believe", "fraction", "forest", "sit", "race", "window", "store", "summer", "train", "sleep", "prove", "lone", "leg", "exercise", "wall", "catch", "mount", "wish", "sky", "board", "joy", "winter", "sat", "written", "wild", "instrument", "kept", "glass", "grass", "cow", "job", "edge", "sign", "visit", "past", "soft", "fun", "bright", "gas", "weather", "month", "million", "bear", "finish", "happy", "hope", "flower", "clothe", "strange", "gone", "jump", "baby", "eight", "village", "meet", "root", "buy", "raise", "solve", "metal", "whether", "push", "seven", "paragraph", "third", "shall", "held", "hair", "describe", "cook", "floor", "either", "result", "burn", "hill", "safe", "cat", "century", "consider", "type", "law", "bit", "coast", "copy", "phrase", "silent", "tall", "sand", "soil", "roll", "temperature", "finger", "industry", "value", "fight", "lie", "beat", "excite", "natural", "view", "sense", "ear", "else", "quite", "broke", "case", "middle", "kill", "son", "lake", "moment", "scale", "loud", "spring", "observe", "child", "straight", "consonant", "nation", "dictionary", "milk", "speed", "method", "organ", "pay", "age", "section", "dress", "cloud", "surprise", "quiet", "stone", "tiny", "climb", "cool", "design", "poor", "lot", "experiment", "bottom", "key", "iron", "single", "stick", "flat", "twenty", "skin", "smile", "crease", "hole", "trade", "melody", "trip", "office", "receive", "row", "mouth", "exact", "symbol", "die", "least", "trouble", "shout", "except", "wrote", "seed", "tone", "join", "suggest", "clean", "break", "lady", "yard", "rise", "bad", "blow", "oil", "blood", "touch", "grew", "cent", "mix", "team", "wire", "cost", "lost", "brown", "wear", "garden", "equal", "sent", "choose", "fell", "fit", "flow", "fair", "bank", "collect", "save", "control", "decimal", "gentle", "woman", "captain", "practice", "separate", "difficult", "doctor", "please", "protect", "noon", "whose", "locate", "ring", "character", "insect", "caught", "period", "indicate", "radio", "spoke", "atom", "human", "history", "effect", "electric", "expect", "crop", "modern", "element", "hit", "student", "corner", "party", "supply", "bone", "rail", "imagine", "provide", "agree", "thus", "capital", "won't", "chair", "danger", "fruit", "rich", "thick", "soldier", "process", "operate", "guess", "necessary", "sharp", "wing", "create", "neighbor", "wash", "bat", "rather", "crowd", "corn", "compare", "poem", "string", "bell", "depend", "meat", "rub", "tube", "famous", "dollar", "stream", "fear", "sight", "thin", "triangle", "planet", "hurry", "chief", "colony", "clock", "mine", "tie", "enter", "major", "fresh", "search", "send", "yellow", "gun", "allow", "print", "dead", "spot", "desert", "suit", "current", "lift", "rose", "continue", "block", "chart", "hat", "sell", "success", "company", "subtract", "event", "particular", "deal", "swim", "term", "opposite", "wife", "shoe", "shoulder", "spread", "arrange", "camp", "invent", "cotton", "born", "determine", "quart", "nine", "truck", "noise", "level", "chance", "gather", "shop", "stretch", "throw", "shine", "property", "column", "molecule", "select", "wrong", "gray", "repeat", "require", "broad", "prepare", "salt", "nose", "plural", "anger", "claim", "continent", "oxygen", "sugar", "death", "pretty", "skill", "women", "season", "solution", "magnet", "silver", "thank", "branch", "match", "suffix", "especially", "fig", "afraid", "huge", "sister", "steel", "discuss", "forward", "similar", "guide", "experience", "score", "apple", "bought", "led", "pitch", "coat", "mass", "card", "band", "rope", "slip", "win", "dream", "evening", "condition", "feed", "tool", "total", "basic", "smell", "valley", "nor", "double", "seat", "arrive", "master", "track", "parent", "shore", "division", "sheet", "substance", "favor", "connect", "post", "spend", "chord", "fat", "glad", "original", "share", "station", "dad", "bread", "charge", "proper", "bar", "offer", "segment", "slave", "duck", "instant", "market", "degree", "populate", "chick", "dear", "enemy", "reply", "drink", "occur", "support", "speech", "nature", "range", "steam", "motion", "path", "liquid", "log", "meant", "quotient", "teeth", "shell", "neck","Airplane","Ears","Piano","Angry","Elephant","Pinch","Baby","Fish","Reach","Ball","Flick","Remote","Baseball","Football","Roll","Basketball","Fork","Sad","Bounce","Giggle","Scissors","Cat","Golf","Skip","Chicken","Guitar","Sneeze","Chimpanzee","Hammer","Spin","Clap","Happy","Spoon","Cough","Horns","Stomp","Cry","Joke","Stop","Dog","Mime","Tail","Drink","Penguin","Toothbrush","Drums","Phone","Wiggle","Duck","Photographer"," Beauty and the Beast","The Jungle Book","The Princess and the Frog","Brave","Lady and the Tramp","Robin Hood","Cinderella","Mulan","Snow White and the Seven Dwarfs","Dumbo","Peter Pan","The Sword in the Stone","Balance beam","Haircut","Shoelaces","Ballet","Halo","Sick","Balloon","Hiccup","Singer","Banana peel","Hot dog","Skateboard","Book","Hungry","Slippery","Braces","Hurt","Soccer","Button","Ice skating","Strong","Car","Karate","Stubbed toe","Cheers","Ladder","Sunshine","Clown","Light bulb","Surprise","Dinosaur","Limbo","Swing","Disco","Macarena","Sword","Dizzy","Paint","Tap dance","Fart","Pirate","Wheelbarrow","Fishing","Read","Wizard of Oz","Gallop","River dance"," Blanket","Helicopter","President","Bright","Hurricane","Rainbow","Bump","Kite","Rollercoaster","Christmas","Light","Shadow","Coffee","Magic","Shopping","Cradle","Makeup","Shuffle","Deer","Marriage","Slice","Drool","Mash","Slip n’ slide","Electric Slide","Measure","Smear","Excitement","Mirror","Spider","Fight Club","Monster","The Lion King","Firefighter","Motorcycle","Trampoline","Flashlight","Nightmare","Waterfall","Garden","Nosey","Window","Giraffe","Overwhelmed","Yo-yo","Heavy","Pancakes","Brushing teeth","Building a sandcastle","Dancing","Driving a car","Opening a gift","Playing baseball","Shoveling snow","Swimming","Skateboarding","Tying a shoe","Walking a dog","Yoga","Bumblebee","Bird","Cat","Cow","Dog","Fish","Giraffe","Horse","Monkey","Rabbit","Spider","Snake","Alice's Adventures in Wonderland","Angelina Ballerina","Captain Underpants","Diary of a Wimpy Kid","Elephant and Piggie","Harry Potter and the Sorcerer's Stone","Holes","Princess Cupcake Jones and the Missing Tutu","The Cat in the Hat","The Giving Tree","The Gruffalo","The Lion, the Witch and the Wardrobe","The Very Hungry Caterpillar","Where the Wild Things Are","Beauty and the Beast","Chicken Little","Cinderella","Goldilocks and The Three Bears","Little Red Riding Hood","Rapunzel","Snow White and the Seven Dwarves","Sleeping Beauty","The Boy Who Cried Wolf","The Emperor's New Clothes","Abraham Lincoln","Albert Einstein","Amelia Earhart","Barack Obama","George Washington","Isaac Newton","Neil Armstrong","Vincent van Gogh","Buckingham Palace","Eiffel Tower","Grand Canyon","Great Wall of China","Mount Everest","Mount Rushmore","Niagra Falls","Seattle Space Needle","Smokey Mountains","Statue of Liberty","Banana","Bubblegum","French fries","Ice cream cone","Jello","Pizza","Popcorn","Sandwich","Spaghetti","Taco","Babe","Bambi","Boss Baby","Cats and Dogs","Finding Nemo","Frozen","Home","Harry Potter and the Goblet of Fire","Moana","Pirates of the Caribbean","Spiderman","Superman","The Karate Kid","The Jungle Book","The Lego Movie","The Lion King","The Little Mermaid","Toy Story","Bruno Mars","Justin Bieber","Katy Perry","Michael Jackson","Rihanna","Taylor Swift","Can't Stop the Feeling","Let it Go","Twinkle, Twinkle, Little Star","You are My Sunshine","Bruno Mars","Justin Bieber","Katy Perry","Michael Jackson","Rihanna","Taylor Swift","Can't Stop the Feeling","Let it Go","Twinkle, Twinkle, Little Star","You are My Sunshine","Bruno Mars","Justin Bieber","Katy Perry","Michael Jackson","Rihanna","Taylor Swift","Can't Stop the Feeling","Let it Go","Twinkle, Twinkle, Little Star","You are My Sunshine",
];

var tooltips = [
    "Object, Package",
    "Family, Society, Group",
    "Woman, Female",
    "Man, Male",
    "Job, Work",
    "Hobbie, Sport, Activity",
    "Fauna, Animals",
    "Flora, Plants, Nature",
    "Literature, Writing, Book",
    "Music, Song, Note",
    "Cinema, Movie, Film, Camera",
    "Arts, Sculpture, Paiting, Drawing",
    "Television, Broadcast, Series",
    "Title, Brand, Name",
    "Idea, Thought, Concept",
    "Expression, Language, Dialog",
    "Place, Location, Country, Flag",
    "Building, Construction, Town",
    "Date, Event, Day",
    "Holiday, Anniversary, Party",
    "Maritime/Water Vehicles, Swim",
    "Flying Vehicle, Fly, Airborne",
    "Road Vehicle, Car",
    "Tools",
    "Games, Toys",
    "Clothes, Accessory, Costume",
    "Food, Edible, Eating",
    "House, Home, Interior, Domestic",
    //
    "Real, Historical",
    "Fictional, Imaginary",
    "Young, New, Child, Baby",
    "Old, Past",
    "Slow, Turtle",
    "Fast, Hare",
    "Defense, Protection, Wall",
    "Conflict, Armed, Combat",
    "Life, Heart, Love",
    "Death, Evil, Sickness",
    "Happy, Positive",
    "Sad, Negative",
    "Computer, Electronics",
    "Industrial, Mechanics",
    "Money, Rich, Expensive",
    "Time, Duration",
    "Religion, Myth, Belief",
    "Power, Politics",
    "Science, Maths, Chemistry",
    "Medical, Medication, Medicine, Cure",
    "Head, Face",
    "Arm, Hand",
    "Torso, Belly, Body",
    "Leg, Foot",
    "Ear, Hear, Sound",
    "Nose, Smell",
    "Eye, Sight, See",
    "Mouth, Taste, Eating",
    //
    "Cloud, Rain, Snow, Cold",
    "Flash, Electricity, Storm, Anger",
    "Night, Evening, Moon",
    "Sun, Hot, Light, Day",
    "Fire, Burn",
    "Water, Liquid, Aquatic",
    "Air, Wind, Blow",
    "Earth, Dirt",
    "Rock, Mineral, Hard",
    "Wood",
    "Metal",
    "Fabric",
    "Plastic, Rubber",
    "Paper, Sheet",
    "Opposites, Inverse",
    "Cut, Separate, Half",
    "Fragment, Multitude, Powder",
    "Part of, Piece of",
    "Inside, Within, Internal",
    "Grid, Network, Prison",
    "Zero, None, Null",
    "One, Unit",
    //
    "Straight Line, Straight",
    "Arch, Curve",
    "Cross, Crossing",
    "Broken Line, Sharp, Uneven",
    "Spiral, Drunkenness, Madness",
    "Sinusoidal, Wavy, River, Hair",
    "Ring, Circle",
    "Round",
    "Triangle",
    "Star",
    "Rectangle, Square",
    "Flat",
    "Cube",
    "Sphere",
    "Pyramid",
    "Cylinder",
    "Cone",
    "Hollow, Drilled, Hole",
    "Big, Taller, Higher",
    "Small, Little, Lower",
    "Big, Wide, Longer",
    "Thin, Narrow, Shorter",
    "Up, Climb, Rise",
    "Down, Descend, Fall",
    "Left, Before, Start",
    "Right, After, End",
    "Rotate, Surround, Cycle",
    "Action",
    //
    "Red",
    "Yellow",
    "Brown",
    "Orange",
    "Green",
    "Blue",
    "Pink",
    "Purple",
    "White",
    "Transparent, Glass, Invisible"
]
