var files = [
	"./1.png",
	"./10.png",
	"./11.png",
	"./12.png",
	"./2.png",
	"./3.png",
	"./4.png",
	"./5.png",
	"./6.jpg",
	"./6.png",
	"./7.png",
	"./8.png",
	"./9.png",
	"./files.js",
	"./index.html",
	"./listfiles.bat",
	"./listfiles.py",
	"amnesia/1.mp4",
	"aof5/1.png",
	"aof5/2.png",
	"aof5/3.png",
	"aof5/4.png",
	"aof5/5.png",
	"aof5/6.png",
	"godblock/1.png",
	"midknights pack/1.png",
	"midknights pack/10.png",
	"midknights pack/11.png",
	"midknights pack/12.png",
	"midknights pack/2.png",
	"midknights pack/3.png",
	"midknights pack/4.png",
	"midknights pack/5.png",
	"midknights pack/6.png",
	"midknights pack/7.png",
	"midknights pack/8.png",
	"midknights pack/9.png",
	"mystical skies/1.png",
	"mystical skies/2.png",
	"oldwebsite/hearthwell.png",
	"oldwebsite/index.html",
	"oldwebsite/navbar.html",
	"oldwebsite/patreon.png",
	"oldwebsite/patreon.svg",
	"oldwebsite/patron.html",
	"oldwebsite/stylesheet.css",
	"oldwebsite/temp3.gif",
	"rebuild/1.png",
	"rebuild/10.png",
	"rebuild/11.png",
	"rebuild/2.png",
	"rebuild/3.png",
	"rebuild/4.png",
	"rebuild/5.png",
	"rebuild/6.png",
	"rebuild/7.png",
	"rebuild/8.png",
	"rebuild/9.png",
	"rebuild/temp26.gif",
	"seed the world/1.png",
	"sevtech ages of the sky/1.png",
	"sevtech ages of the sky/2.png",
	"sevtech ages of the sky/74e0pnrPsd8.yt",
	"stoneblock 2/1.png",
];
